name = "backend"
main = "src/index.ts"
compatibility_date = "2024-10-09"
compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMzQwZWI4YjEtMjZhNy00MTA4LThiODktZTA3ODU0ZTYwYzM4IiwidGVuYW50X2lkIjoiY2Q1NDQ0YjY4ZTI0YTkxOGM0YjNkMzljMGQ2MmRkMzUwMTliNzM1ODFkZTUzZjE2YmQ1Y2FkZDRhYWFlOTk4YyIsImludGVybmFsX3NlY3JldCI6ImQ5OTEyMDRiLTVlNzUtNDZhOC05NjNjLTIzNjRkODJiOGNhMyJ9.R4YqeKoFln0KTEkn0g9Ba0zrEQlslUXl5ygxqX-azSE"
JWT_SECRET = "asdayuyisdasd"


# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1